version: '3'

services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_offers
    networks:
      - net
      
  sanic-users:
     image: tuchka1986/sanic-users
     ports:
     - "8001:8001"
     environment:
       DB_HOST: db
       DB_DATABASE: user_offers
       DB_PORT: 5432
       DB_USER: username
       DB_PASSWORD: password
       TOKEN_KEY: ldngffgjkdfdkldjkfdjk
     networks:
       - net
     command:
       python run.py
     depends_on:
       - db
     restart: always
       
  sanic-offers:
     image: tuchka1986/sanic-offers
     ports:
     - "8002:8002"
     environment:
       DB_HOST: db
       DB_DATABASE: user_offers
       DB_PORT: 5432
       DB_USER: username
       DB_PASSWORD: password
       TOKEN_KEY: ldngffgjkdfdkldjkfdjk
     networks:
       - net
     command:
       python run.py
     depends_on:
       - db
       - sanic-users
     restart: always
       
networks:
  net:
     driver: bridge
